sudo: required
services:
  - docker
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
script:
    - sbt docker:stage
after_success:
  - chmod +x herokuDeplyContainer.sh
  - ./herokuDeplyContainer.sh
branches:
  only:
      - master
