sudo: required
services:
  - docker
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
script:
  - sbt clean compile test
  - sbt docker:publishLocal
after_success:
  - chmod +x scripts/startContainer.sh
  - scripts/startContainer.sh
branches:
  only:
      - master
